name: Deploy after merge

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    name: Deploy to server
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Диагностический шаг – временно, чтобы увидеть данные события
      - name: Debug event info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "PR merged: ${{ github.event.pull_request.merged }}"
          echo "Base ref: ${{ github.event.pull_request.base.ref }}"
          echo "Head ref: ${{ github.event.pull_request.head.ref }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /opt/nginx-proxy-manager/first-repository
            git pull origin main
            docker compose build
            docker compose up -d
            docker system prune -f
